name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: make lint
      - run: go test ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run: xcaddy build --with github.com/luzilla/caddyscope=.
