name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      CLICOLOR: 1
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: crate-ci/typos@v1.50.3
        with:
          files: README.md docs

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: make lint
      - run: go test ./...

  build:
    needs:
      - docs
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run: xcaddy build --with github.com/luzilla/caddyscope=.
